// Generated by https://quicktype.io

export interface IAlbumData {
  id:                number;
  name:              string;
  short_description: string;
  slug:              string;
  musicHub:          IMusicHub;
}

export interface IMusicHub {
  label:          string;
  release:        string;
  release_format: string;
  review:         string;
  mood:           string;
  style:          string;
  loved:          string;
  score:          string;
  score_votes:    string;
  speed:          string;
  genre:          IGenre[];
  images:         IImages;
  type:           string;
}

export interface IGenre {
  id:   number;
  name: string;
  slug: string;
}

export interface IImages {
  thumb:        string;
  thumb_hq:     null;
  thumb_back:   string;
  album_cd_art: string;
  album_case:   string;
  album_face:   string;
  album_flat:   string;
}
